env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[c157d9eaa3cc6a9f0b095cdd71414178a4802fb75df97a3a0680979ad78470910072e6bf4ecb3aa7cfac4a1fc4bde99f]"
  TG_TOKEN: "ENCRYPTED[7cd4d6029748623f01168eb55e6970807efcd3bae446ec8a68a7249e426e645892f65c096ed38135f2b7a8cd2587509b]"
  TG_CHAT_ID: "ENCRYPTED[adb9b324ef9147f24a670d811500958917a7cbd76d33a5b9662ad0bad36ec07804f27e73a01d23f285c2eb675f368e4f]"
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'AnGgIt88'
  timeout_in: 120m
  persistent_worker:
    labels:
      name: NFS-worker
    isolation:
      container:
        image: anggit86/ubuntu:22.04
        cpu: 8
        memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
