env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[!2a003d7bb9acbfc1b8092852e63145acf7d9ca86f0ef2095f95f52337e371941b3c0abf81189a5128d359e6c8eafd210!]"
  TG_TOKEN: "ENCRYPTED[!7f186eca008ff8902ed4c9ac0cc3175fb8e2c7c3bfc3ed85852898705e3270006420ebee29f838e8bade8c1852e82e62!]"
  TG_CHAT_ID: "ENCRYPTED[!0a60ea5fa7e53b43d440d2e91adbada2a367420c3ee5937a21241284e2c24de847e90e312549c60a946224b60a9b9c04!]"
  PAT_KEY: "ENCRYPTED[!199494ae2cd5ae2723605579ea0894f6be7d46a5496ca897e7963811d38d931e22e78c946d7ebbfd052117ed1929a209!]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "BiancaProject Build"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "alanndz"
     - git config --global user.email "alanndz7@gmail.com"

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
