env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[229fc20dfbecfe0684e3652d161aa0f19372ad5ca3c1e893d465f78424849192c722bb4733eaaed6a8da6f7e65ff4f8b]"
  TG_TOKEN: "ENCRYPTED[50f9ef0674b3568c1b875d0995b2b05e26ec73c207751fc67608f303d64e9611fa62c1bdb986fccf7bd46c0b645caa88]"
  TG_CHAT_ID: "ENCRYPTED[e478f3babe9556ad04c5ed1c7c6378c968439c9129f573466c2c3addd9ea933fa6c8f4b0fde47c0e41b82bd71f87337b]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Evolution-X Build"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "ZenkaBestia"
     - git config --global user.email "z.mail.6600@gmail.com"

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
